# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IJK3xBXwaQpOQm5zOW-apC8_eiRu2Ehd
"""

# !pip install streamlit -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.title('Welcome')
#

!wget -q -O - ipv4.icanhazip.com

! streamlit run app.py & npx localtunnel --port 8501
